server:
  port: 8082 #端口
spring:
  mail: #邮件配置
    host: smtp.qq.com  #邮件服务器地址
    protocol: smtp #协议
    default-encoding: UTF-8 #编码格式
    password: regfchuufnaridhi #开通时的授权码
    username: 1350777414@qq.com #发送者邮箱
    port: 587 #端口，不同邮箱端口不同

  #rabbitmq配置
  rabbitmq:
    username: admin
    #密码
    password: sa123
    #服务器地址
    host: 192.168.10.117
    #端口
    port: 15672
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual